import { useState, useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [state, setState] = useState([]);

  useEffect(() => {
    const data = fetch("http://localhost:3000/api/content")
      .then((res) => res.json())
      .then(({ data }) => {
        setState(data);
      });
  }, []);

  console.log("state: ", state);

  return (
    <div className={styles.container}>
      <Head>
        <title>CMS Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {state &&
          state.map((contentElement) => {
            return (
              <div key={contentElement._id}>
                <h3>{contentElement.title}</h3>
                <p>{contentElement.description}</p>
              </div>
            );
          })}
      </main>
    </div>
  );
}
