import Head from "next/head";

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <a href="/admin/pages">Admin Page</a>
      </main>
    </div>
  );
};

export default Home;
