import Head from "next/head";
import Link from "next/link";

export const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Link href="/admin/pages">
          <a>Admin Page</a>
        </Link>
      </main>
    </div>
  );
};

export default Home;
